on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: ['1.9.x', '1.10.x', '1.11.x']
          otp-version: ['22.x', '23.x']
      - run: mix deps.get
      - run: mix test

